spring:
  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        format_sql: true

    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      continue-on-error: true
      data-locations: classpath:sql/data.sql